spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:http://localhost:8088"

# Moved to common config
#  management:
#    tracing:
#      sampling:
#        probability: 1.0

#This is moved to common config
#server:
#  port: 8081 // Moved to common config

#This is moved to common config
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#http://localhost:8082/