server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# http://localhost:9411/zipkin/ -> Zipkin will be running here where logs can be monitored
#management:
#  tracing:
#    sampling:
#      probability: 1.0